name: Daily Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  check-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      rust_version: ${{ steps.run-script.outputs.rust_version }}
      glibc_version: ${{ steps.run-script.outputs.glibc_version }}
      alpine_version: ${{ steps.run-script.outputs.alpine_version }}
      tag: ${{ steps.check-versions.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
    - id: run-script
      run: |
        ./scripts/ci-check-versions.sh
  check-tag-exist:
    runs-on: ubuntu-latest
    needs: check-versions
    outputs:
      tag: ${{ steps.check-tag.outputs.tag }}
    steps:
    - id: check-tag
    - env:
        tag: ${{ needs.check-versions.outputs.tag }}
      uses: tyriis/docker-image-tag-exists@v2.0.0
      with:
        registry: docker.io
        repository: mmta/alpine-glibc
        tag: ${{ env.tag }}
  build:
    runs-on: ubuntu-latest
    needs:
    - check-versions
    - check-tag-exist
    if: ${{ needs.check-tag-exist.outputs.tag == 'not found' }}
    steps:
    - uses: actions/checkout@v4
    - id: build-and-push
      env:
        RUST_VERSION: ${{ needs.check-versions.outputs.rust_version }}
        GLIBC_VERSION: ${{ needs.check-versions.outputs.glibc_version }}
        ALPINE_VERSION: ${{ needs.check-versions.outputs.alpine_version }}
      run: |
        ./scripts/ci-build_push.sh mmta/alpine-glibc
        # ./scripts/ci-build_push.sh mmta/alpine-glibc push

      