FROM rust:slim as glib_version
RUN cat <<"EOF" >/get-ver.sh
#!/bin/bash

glib_ver=$(ldd --version | head -1 | sed 's/.*) //')
rust_ver=$(rustc --version | sed 's/rustc //;s/ .*$//')

re="^[0-9]+([.][0-9]+)([.][0-9]+)?$"

for ver in $glib_ver $rust_ver; do
  [[ $ver =~ $re ]] || {
    echo "Failed to get version from ldd/rustc: $ver"
    exit 1
  }
done

echo glibc=$glib_ver rust=$rust_ver
EOF
RUN chmod +x /get-ver.sh

ENTRYPOINT ["/bin/bash"]

CMD ["/get-ver.sh"]
